const data = {
  name: 'categorias',
  tableName: 'categorias-servicos',
  route: 'categorias-servicos',
  modelName: 'CategoriaServico',
  transformerName: 'CategoriaServicoTransformer',
  controllerName: 'CategoriaServicoController',
  repositoryName: 'CategoriaServicoRepository',
  filterName: 'CategoriaServicoFilter',
  transformName: 'CategoriaServicoTransaformer',
  tableFields: [
    {
      type: 'string',
      name: 'descricao',
      required: true,
      unique: false,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'string',
      name: 'letra',
      required: true,
      unique: false,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'integer',
      name: 'nivel',
      required: true,
      unique: false,
      default: false,
      searchable: true,
      returnTransform: true,
    },
  ],
  seeds: {
    uniqueKey: 'nome',
    items: [{ nome: 'test' }],
  },
}
exports.default = data
