const data = {
  name: 'CheckList',
  tableName: 'checkLists',
  route: 'checkList',
  modelName: 'CheckList',
  transformerName: 'CheckListTransformer',
  controllerName: 'CheckListController',
  repositoryName: 'CheckListRepository',
  filterName: 'CheckListFilter',
  tableFields: [
    {
      type: 'string',
      name: 'nome',
      required: true,
      unique: false,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'number',
      name: 'ordem',
      required: true,
      unique: false,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'number',
      name: 'type',
      required: true,
      unique: false,
      default: 1,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'number',
      name: 'percentual_conclusao',
      required: true,
      unique: false,
      default: 0,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'boolean',
      name: 'concluido',
      required: true,
      unique: false,
      default: 0,
      searchable: true,
      returnTransform: true,
    },
  ],
  seeds: {
    uniqueKey: 'nome',
    items: [{ nome: 'teste' }],
  },
}
exports.default = data
