const data = {
  name: 'servicos',
  tableName: 'servicos',
  route: 'servicos',
  modelName: 'Servicos',
  transformerName: 'ServicosTransformer',
  controllerName: 'ServicosController',
  repositoryName: 'ServicosRepository',
  filterName: 'ServicosFilter',
  transformName: 'ServicosTransaformer',
  tableFields: [
    {
      type: 'string',
      name: 'code',
      required: true,
      unique: true,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'string',
      name: 'descricao',
      required: true,
      unique: true,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'string',
      name: 'unidade',
      required: true,
      unique: false,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    {
      type: 'float',
      name: 'quantidade',
      required: true,
      unique: false,
      default: false,
      searchable: true,
      returnTransform: true,
    },
    // {
    //   type: 'relationship',
    //   name: 'user_id',
    //   references: 'users',
    //   fk: 'id',
    //   typeRelationship: 'hasOne',
    //   onDelete: true,
    //   required: true,
    //   unique: false,
    //   default: false,
    //   searchable: true,
    //   returnTransform: true,
    // },

    // {
    //   type: 'text',
    //   name: 'long_description',
    //   required: false,
    //   unique: false,
    //   default: false,
    // },
    // { type: 'integer', name: 'tipo', required: false, unique: false, default: 2 },
    // { type: 'float', name: 'ponto_flutuante', required: true, unique: false, default: 2 },
    // {
    //   type: 'dateTime',
    //   name: 'data_inicio_default',
    //   required: true,
    //   unique: false,
    //   default: true,
    //   isDate: true,
    // },
    // {
    //   type: 'dateTime',
    //   name: 'data_inicio_obrigatoria',
    //   required: true,
    //   default: false,
    //   isDate: true,
    // },
  ],
  seeds: {
    uniqueKey: 'code',
    items: [
      {
        code: '401001',
        descricao: 'ALVENARIA BLOCO DE CERAMICOS e=9cm',
        unidade: 'M2',
        quantidade: '40',
      },
      { code: '401042', descricao: 'ENCUNHAMENTO DE ALVENARIA', unidade: 'M', quantidade: '40' },
      { code: '301031', descricao: 'COMCRETO 20 MPA', unidade: 'M3', quantidade: '40' },
    ],
  },
}
exports.default = data
